ingress:
  enabled: false
#   gateway: # istio gateway to use
#   urls:
#     grafana: # grafana url to expose
kube-prometheus-stack:
  grafana:
    dashboardsConfigMaps:
      dashboard-istio-services: "istio-services-grafana-dashboards"
      dashboard-istio-performance: "istio-grafana-dashboards"
    
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: istio-services
          orgId: 1
          folder: istio        
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/dashboard-istio-services
        - name: istio
          orgId: 1
          folder: istio        
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/dashboard-istio-performance

  prometheus:
    prometheusSpec:
      enableRemoteWriteReceiver: true
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}

loki:
  deploymentMode: SingleBinary
  loki:
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
    schemaConfig:
      configs:
        - from: 2024-04-01
          object_store: filesystem
          store: tsdb
          schema: v13
          index:
            prefix: index_
            period: 24h
    auth_enabled: false
  write:
    replicas: 0
  read:
    replicas: 0
  backend:
    replicas: 0
  singleBinary:
    replicas: 1