{
 "title": "Istio Control Plane Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Deployed Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pilot Versions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(istio_build{component=\"pilot\"}) by (tag)",
     "legendFormat": "{{ tag }}"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{app=\"istiod\"}",
       "legendFormat": "Virtual Memory"
      },
      {
       "expr": "process_resident_memory_bytes{app=\"istiod\"}",
       "legendFormat": "Resident Memory"
      },
      {
       "expr": "go_memstats_alloc_bytes{app=\"istiod\"}",
       "legendFormat": "Alloc"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{app=\"istiod\"}",
       "legendFormat": "Heap in-use"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{app=\"istiod\"}",
       "legendFormat": "Stack in-use"
      },
      {
       "expr": "container_memory_working_set_bytes{container=~\"discovery\", pod=~\"istiod-.*|istio-pilot-.*\"}",
       "legendFormat": "Discovery (container)"
      },
      {
       "expr": "container_memory_working_set_bytes{container=~\"istio-proxy\", pod=~\"istiod-.*|istio-pilot-.*\"}",
       "legendFormat": "Sidecar (container)"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"discovery\", pod=~\"istiod-.*|istio-pilot-.*\"}[1m]))",
       "legendFormat": "Discovery (container)"
      },
      {
       "expr": "irate(process_cpu_seconds_total{app=\"istiod\"}[1m])",
       "legendFormat": "Discovery (process)"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"istio-proxy\", pod=~\"istiod-.*|istio-pilot-.*\"}[1m]))",
       "legendFormat": "Sidecar (container)"
      }
     ]
    },
    {
     "title": "Disk",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_fs_usage_bytes{container=\"discovery\", pod=~\"istiod-.*|istio-pilot-.*\"}",
       "legendFormat": "Discovery"
      },
      {
       "expr": "container_fs_usage_bytes{container=\"istio-proxy\", pod=~\"istiod-.*|istio-pilot-.*\"}",
       "legendFormat": "Sidecar"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{app=\"istiod\"}",
       "legendFormat": "Number of Goroutines"
      }
     ]
    }
   ]
  },
  {
   "title": "Pilot Push Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pilot Pushes",
     "type": "timeseries",
     "description": "Shows the rate of pilot pushes",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(pilot_xds_pushes{type=\"cds\"}[1m]))",
       "legendFormat": "Cluster"
      },
      {
       "expr": "sum(irate(pilot_xds_pushes{type=\"eds\"}[1m]))",
       "legendFormat": "Endpoints"
      },
      {
       "expr": "sum(irate(pilot_xds_pushes{type=\"lds\"}[1m]))",
       "legendFormat": "Listeners"
      },
      {
       "expr": "sum(irate(pilot_xds_pushes{type=\"rds\"}[1m]))",
       "legendFormat": "Routes"
      },
      {
       "expr": "sum(irate(pilot_xds_pushes{type=\"sds\"}[1m]))",
       "legendFormat": "Secrets"
      },
      {
       "expr": "sum(irate(pilot_xds_pushes{type=\"nds\"}[1m]))",
       "legendFormat": "Nametables"
      }
     ]
    },
    {
     "title": "Pilot Errors",
     "type": "timeseries",
     "description": "Captures a variety of pilot errors",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pilot_xds_cds_reject{app=\"istiod\"}) or (absent(pilot_xds_cds_reject{app=\"istiod\"}) - 1)",
       "legendFormat": "Rejected CDS Configs"
      },
      {
       "expr": "sum(pilot_xds_eds_reject{app=\"istiod\"}) or (absent(pilot_xds_eds_reject{app=\"istiod\"}) - 1)",
       "legendFormat": "Rejected EDS Configs"
      },
      {
       "expr": "sum(pilot_xds_rds_reject{app=\"istiod\"}) or (absent(pilot_xds_rds_reject{app=\"istiod\"}) - 1)",
       "legendFormat": "Rejected RDS Configs"
      },
      {
       "expr": "sum(pilot_xds_lds_reject{app=\"istiod\"}) or (absent(pilot_xds_lds_reject{app=\"istiod\"}) - 1)",
       "legendFormat": "Rejected LDS Configs"
      },
      {
       "expr": "sum(rate(pilot_xds_write_timeout{app=\"istiod\"}[1m]))",
       "legendFormat": "Write Timeouts"
      },
      {
       "expr": "sum(rate(pilot_total_xds_internal_errors{app=\"istiod\"}[1m]))",
       "legendFormat": "Internal Errors"
      },
      {
       "expr": "sum(rate(pilot_total_xds_rejects{app=\"istiod\"}[1m]))",
       "legendFormat": "Config Rejection Rate"
      },
      {
       "expr": "sum(rate(pilot_xds_push_context_errors{app=\"istiod\"}[1m]))",
       "legendFormat": "Push Context Errors"
      },
      {
       "expr": "sum(rate(pilot_xds_write_timeout{app=\"istiod\"}[1m]))",
       "legendFormat": "Push Timeouts"
      }
     ]
    },
    {
     "title": "Proxy Push Time",
     "type": "timeseries",
     "description": "Shows the total time it takes to push a config update to a proxy",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(pilot_proxy_convergence_time_bucket[1m])) by (le))",
       "legendFormat": "p50 "
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(pilot_proxy_convergence_time_bucket[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pilot_proxy_convergence_time_bucket[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(pilot_proxy_convergence_time_bucket[1m])) by (le))",
       "legendFormat": "p99.9"
      }
     ]
    },
    {
     "title": "Conflicts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pilot_conflict_inbound_listener{app=\"istiod\"}",
       "legendFormat": "Inbound Listeners"
      },
      {
       "expr": "pilot_conflict_outbound_listener_tcp_over_current_tcp{app=\"istiod\"}",
       "legendFormat": "Outbound Listeners (tcp over current tcp)"
      }
     ]
    },
    {
     "title": "ADS Monitoring",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(pilot_virt_services{app=\"istiod\"})",
       "legendFormat": "Virtual Services"
      },
      {
       "expr": "avg(pilot_services{app=\"istiod\"})",
       "legendFormat": "Services"
      },
      {
       "expr": "sum(pilot_xds{app=\"istiod\"}) by (pod)",
       "legendFormat": "Connected Endpoints {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Envoy Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Envoy Details",
     "type": "timeseries",
     "description": "Shows details about Envoy proxies in the mesh",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(envoy_cluster_upstream_cx_total{cluster_name=\"xds-grpc\"}[1m]))",
       "legendFormat": "XDS Connections"
      },
      {
       "expr": "sum(irate(envoy_cluster_upstream_cx_connect_fail{cluster_name=\"xds-grpc\"}[1m]))",
       "legendFormat": "XDS Connection Failures"
      },
      {
       "expr": "sum(increase(envoy_server_hot_restart_epoch[1m]))",
       "legendFormat": "Envoy Restarts"
      }
     ]
    },
    {
     "title": "XDS Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(envoy_cluster_upstream_cx_active{cluster_name=\"xds-grpc\"})",
       "legendFormat": "XDS Active Connections"
      }
     ]
    },
    {
     "title": "XDS Requests Size",
     "type": "timeseries",
     "description": "Shows the size of XDS requests and responses",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "max(rate(envoy_cluster_upstream_cx_rx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
       "legendFormat": "XDS Response Bytes Max"
      },
      {
       "expr": "quantile(0.5, rate(envoy_cluster_upstream_cx_rx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
       "legendFormat": "XDS Response Bytes Average"
      },
      {
       "expr": "max(rate(envoy_cluster_upstream_cx_tx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
       "legendFormat": "XDS Request Bytes Max"
      },
      {
       "expr": "quantile(.5, rate(envoy_cluster_upstream_cx_tx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
       "legendFormat": "XDS Request Bytes Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Webhooks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Configuration Validation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(galley_validation_passed[1m]))",
       "legendFormat": "Validations (Success)"
      },
      {
       "expr": "sum(rate(galley_validation_failed[1m]))",
       "legendFormat": "Validation (Failure)"
      }
     ]
    },
    {
     "title": "Sidecar Injection",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(sidecar_injection_success_total[1m]))",
       "legendFormat": "Injections (Success)"
      },
      {
       "expr": "sum(rate(sidecar_injection_failure_total[1m]))",
       "legendFormat": "Injections (Failure)"
      }
     ]
    }
   ]
  }
 ]
}