apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}
  labels:
    clrslate.io/managed-dns: enabled
spec:
  selector:
    istio: {{ .Values.istio.gatewaySelector }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.{{ .Values.ingress.domain }}"
  {{- if .Values.httpsRedirection }}
    tls:
      httpsRedirect: true
  {{- end }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "{{ .Release.Name }}-tls"
    hosts:
    - "*.{{ .Values.ingress.domain }}"