apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certificate.issuerName }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.notification.email }}
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: {{ .Values.apiToken.secretName }}
            key: {{ .Values.apiToken.secretKey }}