apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.14.1
        args:
        - --log-level={{ .Values.logging.level }}
        - --log-format={{ .Values.logging.format }}
        - --registry={{ .Values.dns.registry }}
        {{- range .Values.dns.sources }}
        - --source={{ . }}
        {{- end }}
        {{- if .Values.clusterName }}
        - --txt-owner-id={{ .Values.clusterName }}
        {{- end }}
        {{- if .Values.dns.annotationFilter }}
        - --annotation-filter={{ .Values.dns.annotationFilter }}
        {{- end }}
        {{- if .Values.dns.labelFilter }}
        - --label-filter={{ .Values.dns.labelFilter }}
        {{- end }}
        {{- range .Values.dns.domainFilters }}
        - --domain-filter={{ . }}
        {{- end }}
        {{- range .Values.dns.excludeDomains }}
        - --exclude-domains={{ . }}
        {{- end }}
        - --provider={{.Values.dns.provider }}
        {{- if eq .Values.dns.provider "cloudflare" }}
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cloudflare.apiToken.secretName }}
              key: {{ .Values.cloudflare.apiToken.secretKey }}
        {{- end }}
